---
driver:
  name: ec2

provisioner:
  product_name: chef
  product_version: 14.3.37

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-xxx
  - name: ubuntu-16.04
    driver:
      image_id: ami-xxx

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
