name             'app_ror'
maintainer       'Earth U'
maintainer_email 'iskitingbords@gmail.com'
license          'Apache-2.0'
description      'Wrapper cookbook for setting up Ruby on Rails apps'
source_url       'https://github.com/nollieheel/app-ror'
issues_url       'https://github.com/nollieheel/app-ror/issues'
version          '3.1.0'

depends 'git',        '~> 11.0.1'
depends 'ruby_build', '~> 2.1.4'
depends 'nodejs',     '~> 9.0.0'
depends 'yarn',       '~> 0.4.3'

chef_version '>= 16.0'
supports     'ubuntu', '20.04'
